"""The whitelist: whose signature MediaForge believes.

This file is the trust root of the whole module system. A module is "official"
because a key in ``BUILTIN_KEYS`` signed it — not because a store said so, and
not because the module's folder is called something official-sounding. Shipping
the keys *inside MediaForge* is what makes that claim un-forgeable by whoever
happens to be serving an index.json.

Adding a maintainer key here is therefore a code change, reviewed like any other
— which is exactly the ceremony it deserves. Generate it with the store tooling:

    mfstore key gen --name "Your Name" --tiers official,verified
    mfstore key export <key_id> --python     # prints the block to paste below

The private half never leaves the machine that generated it, and nothing in
MediaForge can sign anything: this module only ever *verifies*.

── Admin-added keys ────────────────────────────────────────────────────────
An admin can trust additional keys at runtime (their own module store, a
company's internal one, a fork's maintainer) via the
``module_store_trusted_keys`` setting — a JSON list of the same shape, pasted
into the Module Manager. Those keys are *not* capped: an admin who registers a
key as "official" gets official modules from it.

That is a deliberate change from "capped at verified", and worth being honest
about. The argument for the cap was that "official" should mean *the MediaForge
maintainers vouch*, and no setting on somebody's own server can make that true.
The argument against it — which won — is that a self-hosted admin running their
own store is not being lied to by their own key: they chose it, and refusing to
honour their choice just meant their own modules were permanently second-class
on their own install. Trust that an admin deliberately configured is trust they
are entitled to configure.

What is preserved: a *store* still cannot promote itself. Pointing MediaForge at
a repository does nothing to what it trusts — the key has to be pasted in here,
by hand, by an admin, which is the same act as installing the module by hand.
And a built-in key always wins a key_id collision, so an admin setting can never
shadow a maintainer key with one of their own. See trusted_keys().
"""

import json

from ...logger import get_logger

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Maintainer keys. Empty on purpose: the real ones must be generated by the
# people who will hold the private halves, and pasted in by them. Until one is
# here, *nothing* verifies as official — which is the honest state of affairs,
# not a bug. See this module's docstring for the two commands that produce a
# block to paste here.
#
# Shape (public_key is base64 of the raw 32-byte Ed25519 public key):
#
#     {
#         "key_id": "3f2a9c1d8b4e5a60",
#         "name": "Domekologe",
#         "public_key": "kR2h…",
#         "tiers": ("official", "verified"),
#     },
#
# `tiers` is what a key is *allowed* to assert. A reviewer key that should only
# be able to bless third-party submissions gets ("verified",) and can then not
# mint an official module even if it signs a document claiming that tier —
# signing.py checks the tier against this list, not against the document.
# ---------------------------------------------------------------------------
BUILTIN_KEYS = [
    # {
    #     "key_id": "…",
    #     "name": "…",
    #     "public_key": "…",
    #     "tiers": ("official", "verified"),
    # },
]

ADMIN_KEYS_SETTING = "module_store_trusted_keys"

# Tiers an admin-added key may assert. Both, now -- see this module's docstring
# for why the "verified" cap was dropped. An entry that names neither gets
# "verified", the safer of the two, rather than an empty (useless) tier list.
_ADMIN_ALLOWED_TIERS = ("official", "verified")


def _admin_keys() -> list:
    """Extra keys an admin trusts on this install (a private/company store).

    Malformed JSON here must not break module loading — an admin fat-fingering a
    setting should cost them their extra keys, not their MediaForge.
    """
    try:
        from ..db import get_setting

        raw = get_setting(ADMIN_KEYS_SETTING, "") or ""
        if not raw.strip():
            return []
        entries = json.loads(raw)
    except Exception:
        logger.exception("[Signing] Could not read %s — ignoring admin-added keys",
                         ADMIN_KEYS_SETTING)
        return []

    out = []
    for entry in entries if isinstance(entries, list) else []:
        key_id = str(entry.get("key_id") or "").strip()
        public_key = str(entry.get("public_key") or "").strip()
        if not key_id or not public_key:
            continue
        tiers = tuple(t for t in (entry.get("tiers") or ()) if t in _ADMIN_ALLOWED_TIERS)
        out.append({
            "key_id": key_id,
            "name": str(entry.get("name") or key_id),
            "public_key": public_key,
            # An entry that asks for a tier this MediaForge doesn't know (or for
            # none at all) falls back to "verified" -- the weaker claim -- rather
            # than to nothing, which would make the key silently useless.
            "tiers": tiers or ("verified",),
            "admin_added": True,
        })
    return out


def trusted_keys() -> dict:
    """Every key this install trusts, keyed by key_id: built-in first, admin-added
    second — and a built-in key wins a key_id collision, so an admin setting can
    never quietly shadow a maintainer key with one of their own."""
    keys = {}
    for entry in _admin_keys():
        keys[entry["key_id"]] = entry
    for entry in BUILTIN_KEYS:
        keys[entry["key_id"]] = {**entry, "admin_added": False}
    return keys
